import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/Footer.tsx
import { useEffect, useState } from "react";
const Footer = () => {
    const [year, setYear] = useState(new Date().getFullYear());
    useEffect(() => {
        setYear(new Date().getFullYear());
    }, []);
    return (_jsx("footer", { className: "text-white py-8 mt-12 bg-[#111111]", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h3", { className: "text-xl font-semibold mb-3 text-center sm:text-left", children: "Connect with Us" }), _jsxs("div", { className: "flex flex-wrap justify-center sm:justify-start gap-4 sm:gap-6", children: [_jsxs("a", { href: "https://facebook.com", target: "_blank", className: "hover:text-blue-400 flex items-center space-x-2", rel: "noreferrer", children: [_jsx("i", { className: "fab fa-facebook-f fa-lg" }), _jsx("span", { children: "Facebook" })] }), _jsxs("a", { href: "https://www.instagram.com/shop.lootara/", target: "_blank", className: "hover:text-pink-400 flex items-center space-x-2", rel: "noreferrer", children: [_jsx("i", { className: "fab fa-instagram fa-lg" }), _jsx("span", { children: "Instagram" })] }), _jsxs("a", { href: "https://x.com", target: "_blank", className: "hover:text-blue-300 flex items-center space-x-2", rel: "noreferrer", children: [_jsx("i", { className: "fab fa-x-twitter fa-lg" }), _jsx("span", { children: "X" })] }), _jsxs("a", { href: "https://whatnot.com/invite/lootara", target: "_blank", className: "hover:text-yellow-400 flex items-center space-x-2", rel: "noreferrer", children: [_jsx("i", { className: "fas fa-store fa-lg" }), _jsx("span", { children: "Whatnot" })] })] })] }), _jsxs("div", { className: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-4 mt-6 text-sm text-gray-300", children: [_jsx("a", { href: "/terms-and-condition", className: "hover:underline", children: "Terms & Conditions" }), _jsx("a", { href: "/shipping-returns", className: "hover:underline", children: "Shipping & Returns" }), _jsx("a", { href: "/faqs", className: "hover:underline", children: "FAQs" }), _jsx("a", { href: "/privacy", className: "hover:underline", children: "Privacy Policy" }), _jsx("a", { href: "/about-us", className: "hover:underline", children: "About Us" }), _jsx("a", { href: "/reviews", className: "hover:underline", children: "Reviews" })] }), _jsxs("div", { className: "mt-6 text-sm text-gray-500 text-center", children: ["\u00A9 ", year, " Lootara. All rights reserved."] })] }) }));
};
export default Footer;
